/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Ciudad;
import modelo.Cliente;
import modelo.Comuna;
import modelo.Region;
import modelo.Vendedor;
import modelo.Validaciones;
import modeloDAO.ClienteDAO;
import modeloDAO.VendedorDAO;

/**
 *
 * @author franc
 */
public class AddVendedor extends javax.swing.JFrame {

    // Variable para almacenar el codigo de la region en el combo.
    int codReg;
    int codCiud;

    /**
     * Creates new form addVendedor
     */
    public AddVendedor() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        // Se asignan las credenciales de Usuario al titulo de la Interfaz.
        this.setTitle("Añadir Cliente: " + Login.identificador_usuario);
        jLabel_identificador_usuario.setText(Login.identificador_usuario);

        // Traemos la fecha y hora en un String desde Validaciones.getFecha()
        jLabel_fecha.setText(Validaciones.getFecha());

        // Se carga el comboBox de Region
        //caragaRegion();
        Region reg = new Region();
        DefaultComboBoxModel modeloReg = new DefaultComboBoxModel(reg.cargaComboRegiones());
        cbxRegion.setModel(modeloReg);

        // Se blquean los comboBox de Ciudad y Comuna.
        cbxCiudad.setEnabled(false);
        cbxComuna.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel_identificador_usuario = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        txt_apellidoPat = new javax.swing.JTextField();
        txt_apellidoMat = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_rut = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_DV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_telefono1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_addVendedor = new javax.swing.JButton();
        cbxRegion = new javax.swing.JComboBox<>();
        cbxCiudad = new javax.swing.JComboBox<>();
        cbxComuna = new javax.swing.JComboBox<>();
        txt_username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        cbxSucursal = new javax.swing.JComboBox<>();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("Interfaz Añadir Vendedor");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel_identificador_usuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_identificador_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 30));

        jLabel_fecha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 241, 39));

        txt_nombres.setBackground(new java.awt.Color(0, 102, 153));
        txt_nombres.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_nombres.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombresKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 110, 160, -1));

        txt_apellidoPat.setBackground(new java.awt.Color(0, 102, 153));
        txt_apellidoPat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_apellidoPat.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellidoPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoPatKeyTyped(evt);
            }
        });
        getContentPane().add(txt_apellidoPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 163, 160, -1));

        txt_apellidoMat.setBackground(new java.awt.Color(0, 102, 153));
        txt_apellidoMat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_apellidoMat.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellidoMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoMatKeyTyped(evt);
            }
        });
        getContentPane().add(txt_apellidoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 213, 160, -1));

        txt_direccion.setBackground(new java.awt.Color(0, 102, 153));
        txt_direccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 266, 160, -1));

        txt_email.setBackground(new java.awt.Color(0, 102, 153));
        txt_email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 319, 160, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido Materno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 221, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Direccion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 323, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido Paterno:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 167, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombres:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 114, -1, -1));

        txt_rut.setBackground(new java.awt.Color(0, 204, 204));
        txt_rut.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_rut.setForeground(new java.awt.Color(255, 255, 255));
        txt_rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rutKeyTyped(evt);
            }
        });
        getContentPane().add(txt_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 160, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 15, -1));

        txt_DV.setBackground(new java.awt.Color(0, 204, 204));
        txt_DV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_DV.setForeground(new java.awt.Color(255, 255, 255));
        txt_DV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DVKeyTyped(evt);
            }
        });
        getContentPane().add(txt_DV, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 24, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rut:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        txt_telefono1.setBackground(new java.awt.Color(0, 204, 204));
        txt_telefono1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_telefono1.setForeground(new java.awt.Color(255, 255, 255));
        txt_telefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefono1KeyTyped(evt);
            }
        });
        getContentPane().add(txt_telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 160, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono Celular:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        btn_addVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        btn_addVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, -1, -1));

        cbxRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxRegionItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 220, 190, -1));

        cbxCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCiudadItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 260, 190, -1));

        getContentPane().add(cbxComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 300, 190, -1));

        txt_username.setBackground(new java.awt.Color(0, 102, 153));
        txt_username.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usernameKeyTyped(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 160, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Usetname:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Passsword:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        txt_password.setBackground(new java.awt.Color(0, 102, 153));
        txt_password.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 160, -1));

        cbxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Sucursal", "1- Santos Doumont 1244", "2- Av. Pdte. Kennedy Lateral 9001", "3- Vicuña Mackenna 7110" }));
        getContentPane().add(cbxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 360, 190, -1));

        jLabel_fondo.setForeground(new java.awt.Color(0, 204, 204));
        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Venice Blue.jpg"))); // NOI18N
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombresKeyTyped
        Validaciones.validarLetras(evt);
    }//GEN-LAST:event_txt_nombresKeyTyped

    private void txt_apellidoPatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoPatKeyTyped
        Validaciones.validarLetras(evt);
    }//GEN-LAST:event_txt_apellidoPatKeyTyped

    private void txt_apellidoMatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoMatKeyTyped
        Validaciones.validarLetras(evt);
    }//GEN-LAST:event_txt_apellidoMatKeyTyped

    private void txt_rutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rutKeyTyped
        Validaciones.validarNumero(evt);
    }//GEN-LAST:event_txt_rutKeyTyped

    private void txt_DVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DVKeyTyped
        Validaciones.validarDV(evt, txt_DV.getText());
    }//GEN-LAST:event_txt_DVKeyTyped

    private void txt_telefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono1KeyTyped
        Validaciones.validarNumero(evt);
    }//GEN-LAST:event_txt_telefono1KeyTyped

    private void btn_addVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addVendedorActionPerformed

        if (validarCampos()) {
            if (Validaciones.validarEmail(txt_email.getText())) {
                JOptionPane.showMessageDialog(null, "Eso es un correo");
                /*
                * Asignar un metodo de validacion que verifique si el Cliente ya
                * existe en la base de datos, si es asi denegar la opcion de añadir al cliente.
                 */

                // Se revisa que el cliente exista o no en la BD en base al RUT
                if (VendedorDAO.checkVendedor(txt_rut.getText() + "-" + txt_DV.getText())) {
                    // Existe NO se puede
                    JOptionPane.showMessageDialog(null, "El Vendedor ya esta registrado bajo ese RUT", "Vendedor Existente", JOptionPane.WARNING_MESSAGE);
                } else {
                    // Esta Libre

                    if (cbxComuna.getSelectedIndex() >= 1) {
                        addVendedor();
                        //addedVendedor();

                    } else {

                        JOptionPane.showMessageDialog(null, "La comuna seleccionada aun no a sido introducida\n"
                                + "a nuestro sistema :(");
                    }

                }

            } else {
                JOptionPane.showMessageDialog(null, "EL correo ingresado no es valido", "Correo Invalido!",
                        JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Se deben llenar todos los cmapos.", "Campos Vacios",
                    JOptionPane.WARNING_MESSAGE);
            limpiarCampos();
        }
    }//GEN-LAST:event_btn_addVendedorActionPerformed

    private void cbxCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCiudadItemStateChanged
        cbxComuna.setEnabled(true);
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Ciudad ciud = (Ciudad) cbxCiudad.getSelectedItem();
            codCiud = cbxCiudad.getSelectedIndex();

            Comuna comu = new Comuna();
            DefaultComboBoxModel modComuna = new DefaultComboBoxModel(comu.cargaComboComunas(ciud.getCodCiudad()));

            cbxComuna.setModel(modComuna);

        }

    }//GEN-LAST:event_cbxCiudadItemStateChanged

    private void cbxRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxRegionItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            cbxCiudad.setEnabled(true);
            Region reg = (Region) cbxRegion.getSelectedItem();
            codReg = cbxRegion.getSelectedIndex();

            Ciudad ciud = new Ciudad();
            DefaultComboBoxModel modCiudad = new DefaultComboBoxModel(ciud.cargaComboCiudades(reg.getCodRegion()));

            cbxCiudad.setModel(modCiudad);
        }
    }//GEN-LAST:event_cbxRegionItemStateChanged

    private void txt_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addVendedor;
    private javax.swing.JComboBox<String> cbxCiudad;
    private javax.swing.JComboBox<String> cbxComuna;
    private javax.swing.JComboBox<String> cbxRegion;
    private javax.swing.JComboBox<String> cbxSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_identificador_usuario;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JTextField txt_DV;
    private javax.swing.JTextField txt_apellidoMat;
    private javax.swing.JTextField txt_apellidoPat;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_rut;
    private javax.swing.JTextField txt_telefono1;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para limpiar los campos de la interfaz.
     */
    private void limpiarCampos(){
        txt_DV.setText("");
        txt_apellidoMat.setText("");
        txt_apellidoPat.setText("");
        txt_direccion.setText("");
        txt_email.setText("");
        txt_nombres.setText("");
        txt_rut.setText("");
        txt_telefono1.setText("");
        txt_username.setText("");
        txt_password.setText("");

        txt_DV.setBackground(new Color(0, 204, 204));
        txt_apellidoMat.setBackground(new Color(0, 102, 153));
        txt_apellidoPat.setBackground(new Color(0, 102, 153));
        txt_direccion.setBackground(new Color(0, 102, 153));
        txt_email.setBackground(new Color(0, 102, 153));
        txt_nombres.setBackground(new Color(0, 102, 153));
        txt_username.setBackground(new Color(0, 102, 153));
        txt_password.setBackground(new Color(0, 102, 153));
        
        txt_rut.setBackground(new Color(0, 204, 204));
        txt_telefono1.setBackground(new Color(0, 204, 204));
        
        cbxCiudad.setEnabled(false);
        cbxComuna.setEnabled(false);
        
    }
    
    
    private boolean validarCampos() {
        boolean x = true;

        if (!Validaciones.validarTxt(txt_DV.getText())) {
            txt_DV.setBackground(Color.red);
            x = false;
        }
        if (!Validaciones.validarTxt(txt_rut.getText())) {
            txt_rut.setBackground(Color.red);
            x = false;
        }
        if (!Validaciones.validarTxt(txt_nombres.getText())) {
            txt_nombres.setBackground(Color.red);
            x = false;
        }
        if (!Validaciones.validarTxt(txt_apellidoPat.getText())) {
            txt_apellidoPat.setBackground(Color.red);
            x = false;
        }
        if (!Validaciones.validarTxt(txt_apellidoMat.getText())) {
            txt_apellidoMat.setBackground(Color.red);
            x = false;
        }
        if (!Validaciones.validarTxt(txt_direccion.getText())) {
            txt_direccion.setBackground(Color.red);
            x = false;
        }
        if (!Validaciones.validarTxt(txt_email.getText())) {
            txt_email.setBackground(Color.red);
            x = false;
        }
        if (!Validaciones.validarTxt(txt_telefono1.getText())) {
            txt_telefono1.setBackground(Color.red);
            x = false;
        }
        if(!Validaciones.validarTxt(txt_username.getText())){
            txt_username.setBackground(Color.red);
            x = false;
        }
        if(!Validaciones.validarTxt(txt_password.getText())){
            txt_password.setBackground(Color.red);
            x = false;
        }
        return x;
    }
    
    private void addVendedor() {
        Vendedor vend = new Vendedor();
        
        //int idCliente = null;
        String rut = txt_rut.getText() + "-" + txt_DV.getText();
        String nombres = txt_nombres.getText();
        String apePat = txt_apellidoPat.getText();
        String apeMat = txt_apellidoMat.getText();
        String direccion = txt_direccion.getText();
        String email = txt_email.getText();
        String username = txt_username.getText();
        String password = txt_password.getText();
        String telefono = txt_telefono1.getText();
        int codComuna = cbxComuna.getSelectedIndex(); //-> Agregar mediante comboBox.!!!!!
        int codSucu = cbxSucursal.getSelectedIndex();
        
        // Añadiendo Cliente al modelo, utilizando el constructor con parametros.
        
        vend.setRutVendedor(rut);
        vend.setNombres(nombres);
        vend.setApellidoPat(apePat);
        vend.setApellidoMat(apeMat);
        vend.setUsername(username);
        vend.setPassword(password);
        vend.setDireccion(direccion);
        vend.setEmail(email);
        vend.setTelefono(telefono);
        vend.setCodComuna(codComuna);
        vend.setIdSucursal(codSucu);
        
        
        VendedorDAO.addVendedor(vend);

    }

    /**
     * Probar incluyendo modelo de combo y region a la logica del llenado.
     */
    public void caragaRegion() {
        Region reg = new Region();
        DefaultComboBoxModel modeloReg = new DefaultComboBoxModel(reg.cargaComboRegiones());
        cbxRegion.setModel(modeloReg);
    }

}
