/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;


import javax.swing.JOptionPane;
import modelo.Validaciones;
/**
 * Clase Que se utiliza para realizar cambios a la info fe un Cliente
 * utilizando CRUD'S a la base de datos, estos CRUD'S son metodos que se
 * encuentran en la clase ClienteDAO
 * @author Francisco
 */
public class GestionarCliente extends javax.swing.JFrame {
    
    public static String clienteUpdate = "";
    String cliente;
    int id;
    
    
    
    /**
     * Creates new form InfoCliente
     */
    public GestionarCliente() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        // Traemos el String identificador_usuario desde el logeo/Validaciones.Username()
        jLabel_identificador_usuario.setText(Login.identificador_usuario);
        // Traemos la fecha y hora en un String desde Validaciones.getFecha()
        jLabel_fecha.setText(Validaciones.getFecha());
        
        //clienteUpdate = cliente seleccionado en la tabla.
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_apellidoPat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_apellidoMat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_rut = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_DV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_telefono1 = new javax.swing.JTextField();
        btnElminarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        jLabel_identificador_usuario = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("Revision Datos Cliente.");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombres:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        txt_nombres.setEditable(false);
        txt_nombres.setBackground(new java.awt.Color(0, 102, 153));
        txt_nombres.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_nombres.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombresKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 160, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido Paterno:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txt_apellidoPat.setEditable(false);
        txt_apellidoPat.setBackground(new java.awt.Color(0, 102, 153));
        txt_apellidoPat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_apellidoPat.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellidoPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoPatKeyTyped(evt);
            }
        });
        getContentPane().add(txt_apellidoPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 160, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido Materno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        txt_apellidoMat.setEditable(false);
        txt_apellidoMat.setBackground(new java.awt.Color(0, 102, 153));
        txt_apellidoMat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_apellidoMat.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellidoMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoMatKeyTyped(evt);
            }
        });
        getContentPane().add(txt_apellidoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 160, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Direccion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        txt_direccion.setEditable(false);
        txt_direccion.setBackground(new java.awt.Color(0, 102, 153));
        txt_direccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 160, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        txt_email.setEditable(false);
        txt_email.setBackground(new java.awt.Color(0, 102, 153));
        txt_email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 160, -1));

        txt_rut.setEditable(false);
        txt_rut.setBackground(new java.awt.Color(0, 204, 204));
        txt_rut.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_rut.setForeground(new java.awt.Color(255, 255, 255));
        txt_rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rutKeyTyped(evt);
            }
        });
        getContentPane().add(txt_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 160, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rut:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 15, -1));

        txt_DV.setEditable(false);
        txt_DV.setBackground(new java.awt.Color(0, 204, 204));
        txt_DV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_DV.setForeground(new java.awt.Color(255, 255, 255));
        txt_DV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DVKeyTyped(evt);
            }
        });
        getContentPane().add(txt_DV, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 24, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        txt_telefono1.setEditable(false);
        txt_telefono1.setBackground(new java.awt.Color(0, 204, 204));
        txt_telefono1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_telefono1.setForeground(new java.awt.Color(255, 255, 255));
        txt_telefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefono1KeyTyped(evt);
            }
        });
        getContentPane().add(txt_telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 160, -1));

        btnElminarCliente.setBackground(new java.awt.Color(255, 51, 51));
        btnElminarCliente.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnElminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnElminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/icDelCLI.png"))); // NOI18N
        btnElminarCliente.setText("Eliminar Cliente");
        btnElminarCliente.setBorder(null);
        btnElminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElminarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnElminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 220, -1));

        btnActualizarCliente.setBackground(new java.awt.Color(0, 102, 255));
        btnActualizarCliente.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        btnActualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/icSettingsCLI.png"))); // NOI18N
        btnActualizarCliente.setText("Actualizar Datos Cliente");
        btnActualizarCliente.setBorder(null);
        getContentPane().add(btnActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 220, -1));

        jLabel_identificador_usuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_identificador_usuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_identificador_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 453, 37));

        jLabel_fecha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 241, 39));

        jLabel_fondo.setForeground(new java.awt.Color(0, 204, 204));
        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Venice Blue.jpg"))); // NOI18N
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombresKeyTyped
        Validaciones.validarLetras(evt);
    }//GEN-LAST:event_txt_nombresKeyTyped

    private void txt_apellidoPatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoPatKeyTyped
        Validaciones.validarLetras(evt);
    }//GEN-LAST:event_txt_apellidoPatKeyTyped

    private void txt_apellidoMatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoMatKeyTyped
        Validaciones.validarLetras(evt);
    }//GEN-LAST:event_txt_apellidoMatKeyTyped

    private void txt_rutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rutKeyTyped
        Validaciones.validarNumero(evt);
    }//GEN-LAST:event_txt_rutKeyTyped

    private void txt_DVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DVKeyTyped
        Validaciones.validarDV(evt, txt_DV.getText());
    }//GEN-LAST:event_txt_DVKeyTyped

    private void txt_telefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono1KeyTyped
        Validaciones.validarNumero(evt);
    }//GEN-LAST:event_txt_telefono1KeyTyped

    private void btnElminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElminarClienteActionPerformed
        
        // Metodo para borrar al cliente (seleccionado desde la tabla) de la base de datos.
        JOptionPane.showConfirmDialog(null, "Esta seguro que desea borrar al cliente??");
        
        
        
    }//GEN-LAST:event_btnElminarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnElminarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_identificador_usuario;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JTextField txt_DV;
    private javax.swing.JTextField txt_apellidoMat;
    private javax.swing.JTextField txt_apellidoPat;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_rut;
    private javax.swing.JTextField txt_telefono1;
    // End of variables declaration//GEN-END:variables
}
