/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import modelo.Validaciones;
import modeloDAO.VendedorDAO;
import modelo.Vendedor;

/**
 *
 * @author franc
 */
public class ListaVendedores extends javax.swing.JFrame {

    public static String identificador_usuario;
    public String fechaOficial;

    public static String vendedorUpdate;

    ArrayList<Vendedor> lista = VendedorDAO.listarVendedores();

    /**
     * Creates new form ListaVendedores
     */
    public ListaVendedores() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setResizable(false);

        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        jLabel_identificador_usuario1.setText(Login.identificador_usuario);

        this.setTitle("Lista Vendedores/ Usuario: " + Login.identificador_usuario);

        // Traemos la fecha y hora en un String desde Validaciones.getFecha()
        jLabel_fecha.setText(Validaciones.getFecha());

        // Metodo para llenar la Tabla con los Vendedores.
        llenarTablaVendedores();

        // Metodo para seleccionar un Vendedor, desde la tabla para modificarlo.
        // este metodo sera instanciado en el constructor, una vez se termine de programar.
        seleccionarVendedor();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_fecha = new javax.swing.JLabel();
        jLabel_identificador_usuario1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Vendedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_fecha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 22, 241, 39));

        jLabel_identificador_usuario1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_identificador_usuario1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_identificador_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 74, 453, 37));

        jScrollPane1.setBackground(new java.awt.Color(0, 102, 204));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTable_Vendedor.setBackground(new java.awt.Color(153, 255, 255));
        jTable_Vendedor.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Vendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id Cliente", "Rut", "Nombres", "Apellido Paterno", "Apellido Materno", "Email", "Direccion", "Codigo Comuna"
            }
        ));
        jScrollPane1.setViewportView(jTable_Vendedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 686, 100));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Para realizar modificaciones a la informacion de los clientes, seleccione un cliente en la tabla.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel_fondo.setForeground(new java.awt.Color(0, 204, 204));
        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Venice Blue.jpg"))); // NOI18N
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaVendedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_identificador_usuario1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Vendedor;
    // End of variables declaration//GEN-END:variables

    public void llenarTablaVendedores() {
        String matrix[][] = new String[lista.size()][5];

        for (int i = 0; i < lista.size(); i++) {
            matrix[i][0] = Integer.toString(lista.get(i).getIdVendedor());
            matrix[i][1] = lista.get(i).getRutVendedor();
            matrix[i][2] = lista.get(i).getNombres();
            matrix[i][3] = lista.get(i).getApellidoPat();
            matrix[i][4] = lista.get(i).getEmail();
        }

        jTable_Vendedor.setModel(new javax.swing.table.DefaultTableModel(
                matrix,
                new String[]{
                    "ID", "Rut", "Nombres", "Apellido Paterno", "Email"
                }
        ));
    }
    
    
    /**
     * Metodo que almacena el rut del vendedor que fue seleccionado en la tabla.
     */
    private void seleccionarVendedor() {
        jTable_Vendedor.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int filaPoint = jTable_Vendedor.rowAtPoint(e.getPoint());
                int columnaPoint = 1; // Numero que indica la columna que queremos reservar!
                
                if (filaPoint > -1) {
                    vendedorUpdate = (String) jTable_Vendedor.getModel().getValueAt(filaPoint, columnaPoint);
                    GestionarVendedor gestVend = new GestionarVendedor();
                    gestVend.setVisible(true);
                }
            }
        });
    }

}
