/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import modelo.Validaciones;

/**
 * Clase Interfaz que funciona como la principal del programa, una vez realizado el ingreso del usuario(vendedor).
 * esta interfaz contiene rutas(botones) hacia todas las distintas interfaces del sistema.
 * @author Francisco
 */
public class Vendedor extends javax.swing.JFrame {

    public static String identificador_usuario;
    public String fechaOficial;
        
    /**
     * Creates new form Vendedor
     */
    public Vendedor() {
        initComponents();
        /*
         * Codigo comuna para todas las interfaces, ver si se puede insertar de otra manera.
        */
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        
        // Metodo para que al cerrar esta interfaz el programa no se detenga.
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        // Metodos para hacer el boton transparente.
        btn_cerrarSesion.setOpaque(false);
        btn_cerrarSesion.setContentAreaFilled(false);
        btn_cerrarSesion.setBorderPainted(false);
        
        // Metodos para hacer los botones tipo icon transparentes.
        linkLB.setOpaque(false);
        linkLB.setContentAreaFilled(false);
        linkLB.setBorderPainted(false);
        
        linkLOS.setOpaque(false);
        linkLOS.setContentAreaFilled(false);
        linkLOS.setBorderPainted(false);
        
        linkLC.setOpaque(false);
        linkLC.setContentAreaFilled(false);
        linkLC.setBorderPainted(false);
        
        linkAC.setOpaque(false);
        linkAC.setContentAreaFilled(false);
        linkAC.setBorderPainted(false);
        
        linkAC.setOpaque(false);
        linkAC.setContentAreaFilled(false);
        linkAC.setBorderPainted(false);
        
        linkGOS.setOpaque(false);
        linkGOS.setContentAreaFilled(false);
        linkGOS.setBorderPainted(false);
        
        
        jLabel_identificador_usuario.setText(Login.identificador_usuario);
        
        
        this.setTitle("Vendedor: " + Login.identificador_usuario);
        
        // Traemos la fecha y hora en un String desde Validaciones.getFecha()
        jLabel_fecha.setText(Validaciones.getFecha());
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_identificador_usuario = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        jLabel_identificador_usuario1 = new javax.swing.JLabel();
        btn_cerrarSesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        linkLB = new javax.swing.JButton();
        linkLOS = new javax.swing.JButton();
        linkLC = new javax.swing.JButton();
        linkAC = new javax.swing.JButton();
        linkGOS = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_ordenServicio = new javax.swing.JMenu();
        men_listaServ = new javax.swing.JMenuItem();
        men_CrearServ = new javax.swing.JMenuItem();
        menu_clientes = new javax.swing.JMenu();
        menu_listaCLi = new javax.swing.JMenuItem();
        mn_addCliente = new javax.swing.JMenuItem();
        menu_boletas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_Vendedores = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Interfaz Vendedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel_identificador_usuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_identificador_usuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_identificador_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 453, 37));

        jLabel_fecha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 241, 39));

        jLabel_identificador_usuario1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_identificador_usuario1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_identificador_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 72, 453, 37));

        btn_cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btn_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/icExit.png"))); // NOI18N
        btn_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Listado Boletas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Listado Ordenes de Servicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Listado Clientes");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Agregar Cliente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Generar Orden Servicio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        linkLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/iconoLB.png"))); // NOI18N
        linkLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkLBActionPerformed(evt);
            }
        });
        getContentPane().add(linkLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 30, 40));

        linkLOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/iconoLOS.png"))); // NOI18N
        linkLOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkLOSActionPerformed(evt);
            }
        });
        getContentPane().add(linkLOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 30, 40));

        linkLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/iconoListClientes.png"))); // NOI18N
        linkLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkLCActionPerformed(evt);
            }
        });
        getContentPane().add(linkLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 30, 40));

        linkAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/iconoAddCliente.png"))); // NOI18N
        linkAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkACActionPerformed(evt);
            }
        });
        getContentPane().add(linkAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 30, 40));

        linkGOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/iconoGOS.png"))); // NOI18N
        linkGOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkGOSActionPerformed(evt);
            }
        });
        getContentPane().add(linkGOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 30, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CERRAR SESION");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jLabel_fondo.setBackground(new java.awt.Color(51, 0, 255));
        jLabel_fondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Venice Blue.jpg"))); // NOI18N
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 560));

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 204));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        menu_ordenServicio.setBackground(new java.awt.Color(0, 204, 204));
        menu_ordenServicio.setForeground(new java.awt.Color(0, 0, 0));
        menu_ordenServicio.setText("Ordenes de Servicio");

        men_listaServ.setBackground(new java.awt.Color(0, 204, 204));
        men_listaServ.setForeground(new java.awt.Color(0, 0, 0));
        men_listaServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/iconoLOS.png"))); // NOI18N
        men_listaServ.setLabel("Listado Ordenes Servicio");
        men_listaServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_listaServActionPerformed(evt);
            }
        });
        menu_ordenServicio.add(men_listaServ);

        men_CrearServ.setBackground(new java.awt.Color(0, 204, 204));
        men_CrearServ.setForeground(new java.awt.Color(0, 0, 0));
        men_CrearServ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/iconoGOS.png"))); // NOI18N
        men_CrearServ.setLabel("Generar Orden de Servicio");
        men_CrearServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_CrearServActionPerformed(evt);
            }
        });
        menu_ordenServicio.add(men_CrearServ);

        jMenuBar1.add(menu_ordenServicio);

        menu_clientes.setBackground(new java.awt.Color(0, 204, 204));
        menu_clientes.setForeground(new java.awt.Color(0, 0, 0));
        menu_clientes.setText("Clientes");
        menu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_clientesActionPerformed(evt);
            }
        });

        menu_listaCLi.setBackground(new java.awt.Color(0, 204, 204));
        menu_listaCLi.setForeground(new java.awt.Color(0, 0, 0));
        menu_listaCLi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/iconoListClientes.png"))); // NOI18N
        menu_listaCLi.setLabel("Lista de Clientes");
        menu_listaCLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_listaCLiActionPerformed(evt);
            }
        });
        menu_clientes.add(menu_listaCLi);

        mn_addCliente.setBackground(new java.awt.Color(0, 204, 204));
        mn_addCliente.setForeground(new java.awt.Color(0, 0, 0));
        mn_addCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/iconoAddCliente.png"))); // NOI18N
        mn_addCliente.setText("Añadir Cliente");
        mn_addCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_addClienteActionPerformed(evt);
            }
        });
        menu_clientes.add(mn_addCliente);

        jMenuBar1.add(menu_clientes);

        menu_boletas.setBackground(new java.awt.Color(0, 204, 204));
        menu_boletas.setForeground(new java.awt.Color(0, 0, 0));
        menu_boletas.setText("Boletas");

        jMenuItem1.setBackground(new java.awt.Color(0, 204, 204));
        jMenuItem1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/iconoLB.png"))); // NOI18N
        jMenuItem1.setText("Listado de boletas");
        menu_boletas.add(jMenuItem1);

        jMenuBar1.add(menu_boletas);

        menu_Vendedores.setBackground(new java.awt.Color(0, 204, 204));
        menu_Vendedores.setForeground(new java.awt.Color(0, 0, 0));
        menu_Vendedores.setText("Vendedores");

        jMenuItem2.setBackground(new java.awt.Color(0, 204, 204));
        jMenuItem2.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem2.setText("Listado Vendedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu_Vendedores.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(0, 204, 204));
        jMenuItem3.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem3.setText("Añadir Vendedor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_Vendedores.add(jMenuItem3);

        jMenuBar1.add(menu_Vendedores);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void men_listaServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_listaServActionPerformed
        /*
        OrdenServicio ordServ = new OrdenServicio();
        ordServ.setVisible(true);
        */
        new ListaOrdenesServicio().setVisible(true);
    }//GEN-LAST:event_men_listaServActionPerformed

    private void men_CrearServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_CrearServActionPerformed
        
        Recepcion recep = new Recepcion();
        recep.setVisible(true);
        
    }//GEN-LAST:event_men_CrearServActionPerformed

    private void menu_listaCLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_listaCLiActionPerformed
        
        ListarClientes listaClientes = new ListarClientes();
        listaClientes.setVisible(true);
        
    }//GEN-LAST:event_menu_listaCLiActionPerformed

    private void mn_addClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_addClienteActionPerformed

        AddCliente addCliente = new AddCliente();
        addCliente.setVisible(true);

    }//GEN-LAST:event_mn_addClienteActionPerformed

    private void menu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_clientesActionPerformed

    private void btn_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarSesionActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarSesionActionPerformed

    private void linkLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkLBActionPerformed
        new ListaBoletas().setVisible(true);
    }//GEN-LAST:event_linkLBActionPerformed

    private void linkLOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkLOSActionPerformed
        new ListaOrdenesServicio().setVisible(true);
    }//GEN-LAST:event_linkLOSActionPerformed

    private void linkLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkLCActionPerformed
        new ListarClientes().setVisible(true);
    }//GEN-LAST:event_linkLCActionPerformed

    private void linkACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkACActionPerformed
        new AddCliente().setVisible(true);
    }//GEN-LAST:event_linkACActionPerformed

    private void linkGOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkGOSActionPerformed
        new Recepcion().setVisible(true);
    }//GEN-LAST:event_linkGOSActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new ListaVendedores().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new AddVendedor().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_identificador_usuario;
    private javax.swing.JLabel jLabel_identificador_usuario1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JButton linkAC;
    private javax.swing.JButton linkGOS;
    private javax.swing.JButton linkLB;
    private javax.swing.JButton linkLC;
    private javax.swing.JButton linkLOS;
    private javax.swing.JMenuItem men_CrearServ;
    private javax.swing.JMenuItem men_listaServ;
    private javax.swing.JMenu menu_Vendedores;
    private javax.swing.JMenu menu_boletas;
    private javax.swing.JMenu menu_clientes;
    private javax.swing.JMenuItem menu_listaCLi;
    private javax.swing.JMenu menu_ordenServicio;
    private javax.swing.JMenuItem mn_addCliente;
    // End of variables declaration//GEN-END:variables
}
