/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistasDEV;

/**
 *
 * @author franc
 */
public class ResaldoComponentes extends javax.swing.JFrame {

    /**
     * Creates new form ResaldoComponentes
     */
    public ResaldoComponentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_abrigos = new javax.swing.JLabel();
        jLabel_precio = new javax.swing.JLabel();
        spinn_abrigos = new javax.swing.JSpinner();
        jLabel_poleras = new javax.swing.JLabel();
        jLabel_precio1 = new javax.swing.JLabel();
        spinn_poleras = new javax.swing.JSpinner();
        jLabel_polerones = new javax.swing.JLabel();
        spinn_polerones = new javax.swing.JSpinner();
        jLabel_precio2 = new javax.swing.JLabel();
        img_abrigos = new javax.swing.JLabel();
        img_poleras = new javax.swing.JLabel();
        img_polerones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_abrigos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_abrigos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_abrigos.setText("Abrigos");

        jLabel_precio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_precio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_precio.setText("Valor: $1800 c/u");

        jLabel_poleras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_poleras.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_poleras.setText("Poleras");

        jLabel_precio1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_precio1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_precio1.setText("Valor: $700 c/u");

        jLabel_polerones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_polerones.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_polerones.setText("Polerones");

        jLabel_precio2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_precio2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_precio2.setText("Valor: $1000c/u");

        img_abrigos.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(img_abrigos)
                            .addGap(200, 200, 200)
                            .addComponent(img_poleras))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_abrigos)
                            .addGap(13, 13, 13)
                            .addComponent(spinn_abrigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(96, 96, 96)
                            .addComponent(jLabel_poleras)
                            .addGap(14, 14, 14)
                            .addComponent(spinn_poleras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(113, 113, 113)
                            .addComponent(jLabel_polerones)
                            .addGap(8, 8, 8)
                            .addComponent(spinn_polerones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel_precio)
                            .addGap(91, 91, 91)
                            .addComponent(jLabel_precio1)
                            .addGap(119, 119, 119)
                            .addComponent(jLabel_precio2)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(img_abrigos)
                        .addComponent(img_poleras))
                    .addGap(144, 144, 144)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spinn_abrigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinn_poleras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_polerones, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinn_polerones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_abrigos)
                                .addComponent(jLabel_poleras))))
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_precio)
                        .addComponent(jLabel_precio1)
                        .addComponent(jLabel_precio2))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResaldoComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResaldoComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResaldoComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResaldoComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResaldoComponentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_abrigos;
    private javax.swing.JLabel img_poleras;
    private javax.swing.JLabel img_polerones;
    private javax.swing.JLabel jLabel_abrigos;
    private javax.swing.JLabel jLabel_poleras;
    private javax.swing.JLabel jLabel_polerones;
    private javax.swing.JLabel jLabel_precio;
    private javax.swing.JLabel jLabel_precio1;
    private javax.swing.JLabel jLabel_precio2;
    private javax.swing.JSpinner spinn_abrigos;
    private javax.swing.JSpinner spinn_poleras;
    private javax.swing.JSpinner spinn_polerones;
    // End of variables declaration//GEN-END:variables
}
